// <auto-generated />
using System;
using AzerothCoreManager.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AzerothCoreManager.Infrastructure.Migrations
{
    [DbContext(typeof(AzerothCoreDbContext))]
    [Migration("20260511105201_AutoGenerateSoapCredentials")]
    partial class AutoGenerateSoapCredentials
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("AzerothCoreManager.Infrastructure.Data.Entities.ManagedStackEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("AdminAccountInitializedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("AuthServerPort")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CoreBranch")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CoreCommitSha")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CoreRepositoryUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomEnvVarsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DatabasePort")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DatabaseRootPassword")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAdminAccountInitialized")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCoreOutdated")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsOutdated")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastBuiltAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastUpdateCheckAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LatestAvailableCoreSha")
                        .HasColumnType("TEXT");

                    b.Property<string>("LatestCoreBuildChecksJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("LatestCoreBuildStatus")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LatestCoreBuildStatusCheckedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxPlayers")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModuleIdsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ModuleVersionsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedStackName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("OutdatedModuleCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OutdatedModulesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RealmName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ServerType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SoapPassword")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SoapPort")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SoapUsername")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StackName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("WorldServerPort")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedStackName")
                        .IsUnique();

                    b.ToTable("ManagedStacks", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
