using System.Text;

namespace AzerothCoreManager.Infrastructure.Services;

/// <summary>
/// Generates docker-compose.override.yml content for AzerothCore stacks.
/// Centralized to avoid duplication between BuildService and StackService.
/// </summary>
public static class DockerComposeOverrideGenerator
{
    public static string GetComposeProjectName(string stackId)
    {
        return $"acore-{stackId}";
    }

    public static string Generate(
        string stackId,
        IReadOnlyDictionary<string, string> customEnvironment,
        string? modulesHostPath = null)
    {
        var composeProjectName = GetComposeProjectName(stackId);
        var sb = new StringBuilder();
        
        sb.AppendLine("# Docker Compose Override - Custom Configuration");
        sb.AppendLine("# Generated by AzerothCore Manager");
        sb.AppendLine();
        sb.AppendLine("services:");

        AppendServiceOverride(sb, "ac-database", $"{composeProjectName}-database");
        AppendServiceOverride(sb, "ac-db-import", $"{composeProjectName}-db-import");
        AppendWorldserverOverride(sb, composeProjectName, customEnvironment, modulesHostPath);
        AppendAuthserverOverride(sb, composeProjectName);
        AppendServiceOverride(sb, "ac-client-data-init", $"{composeProjectName}-client-data-init");
        AppendServiceOverride(sb, "ac-tools", $"{composeProjectName}-tools");
        AppendServiceOverride(sb, "ac-dev-server", $"{composeProjectName}-dev-server");

        return sb.ToString();
    }

    private static void AppendServiceOverride(StringBuilder sb, string serviceName, string containerName)
    {
        sb.AppendLine($"  {serviceName}:");
        sb.AppendLine($"    container_name: {containerName}");
    }

    private static void AppendWorldserverOverride(
        StringBuilder sb,
        string composeProjectName,
        IReadOnlyDictionary<string, string> customEnvironment,
        string? modulesHostPath)
    {
        sb.AppendLine("  ac-worldserver:");
        sb.AppendLine($"    container_name: {composeProjectName}-worldserver");

        // Mount modules directory for SQL migrations (critical for modules like Playerbots)
        sb.AppendLine("    volumes:");
        var modulesMount = modulesHostPath ?? "./modules";
        sb.AppendLine($"      - {modulesMount}:/azerothcore/modules:ro");

        if (customEnvironment.Count == 0)
        {
            return;
        }

        sb.AppendLine("    environment:");
        foreach (var (key, value) in customEnvironment)
        {
            sb.AppendLine($"      {key}: \"{value}\"");
        }
    }

    private static void AppendAuthserverOverride(StringBuilder sb, string composeProjectName)
    {
        sb.AppendLine("  ac-authserver:");
        sb.AppendLine($"    container_name: {composeProjectName}-authserver");
        sb.AppendLine("    ports:");
        sb.AppendLine("      - \"${DOCKER_AUTH_EXTERNAL_PORT}:3724\"");
    }
}
